
sudo: False

language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

install:
    - "pip install coveralls"
    - "pip install coverage"


script:
    - coverage run --source=tests -m py.test -v

after_success:
    - coveralls

notifications:
    - email: false
